create table if not exists public.riverguardian_events (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    local_record_id bigint,
    created_time_s double precision,
    device_id text,
    site_id text,
    node_id text not null,
    distance_cm double precision,
    raw_distance_cm double precision,
    accepted_distance_cm double precision,
    candidate_distance_cm double precision,
    sensor_status text,
    measurement_state text,
    sensor_error text,
    packet_sequence bigint,
    fw_profile text,
    fw_build text,
    clearance_cm double precision,
    rise_rate_cm_min double precision,
    rise_acceleration_cm_min2 double precision,
    time_to_unsafe_min double precision,
    base_risk text,
    fused_risk text,
    rainfall_class text,
    rain_hourly_mm double precision,
    rain_daily_mm double precision,
    temp_c double precision,
    humidity_percent double precision,
    pressure_hpa double precision,
    windspeed_kmh double precision,
    confidence_score integer,
    confidence_level text,
    recommendation_status text,
    public_message text,
    technical_summary text,
    action_level text,
    send_whatsapp boolean not null default false,
    dashboard_priority text,
    alert_should_send boolean not null default false,
    alert_type text,
    alert_reason text,
    alert_message text,
    source text not null default 'UNO_Q',
    payload_version text not null default 'v1'
);

create unique index if not exists riverguardian_events_local_record_id_key
    on public.riverguardian_events (local_record_id)
    where local_record_id is not null;

create index if not exists riverguardian_events_created_at_idx
    on public.riverguardian_events (created_at desc);

create index if not exists riverguardian_events_fused_risk_idx
    on public.riverguardian_events (fused_risk);

create index if not exists riverguardian_events_node_id_idx
    on public.riverguardian_events (node_id);

create index if not exists riverguardian_events_device_id_idx
    on public.riverguardian_events (device_id);

create index if not exists riverguardian_events_site_id_idx
    on public.riverguardian_events (site_id);

alter table public.riverguardian_events enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'riverguardian_events'
          and policyname = 'insert_riverguardian_events'
    ) then
        create policy insert_riverguardian_events
            on public.riverguardian_events
            for insert
            to anon, authenticated
            with check (true);
    end if;
end$$;