-- RiverGuardian Telegram bot platform tables
-- This migration intentionally keeps existing riverguardian_events unchanged.

create table if not exists public.telegram_subscribers (
    id bigint generated by default as identity primary key,
    chat_id bigint not null unique,
    chat_type text,
    telegram_username text,
    first_name text,
    role text not null default 'VIEWER',
    is_authorized boolean not null default false,
    is_active boolean not null default true,
    receive_orange_alerts boolean not null default true,
    receive_red_alerts boolean not null default true,
    receive_device_alerts boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
    id bigint generated by default as identity primary key,
    event_id bigint,
    recipient_chat_id bigint not null,
    platform text not null default 'TELEGRAM',
    message_type text not null,
    sent_at timestamptz not null default now(),
    delivery_status text not null,
    failure_reason text,
    provider_message_id text,
    created_at timestamptz not null default now()
);

create index if not exists telegram_subscribers_authorized_active_idx
    on public.telegram_subscribers (is_authorized, is_active);

create index if not exists notification_deliveries_event_id_idx
    on public.notification_deliveries (event_id);

create index if not exists notification_deliveries_recipient_idx
    on public.notification_deliveries (recipient_chat_id, sent_at desc);

create index if not exists riverguardian_events_alert_dispatch_idx
    on public.riverguardian_events (id asc)
    where alert_should_send = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

do $$
begin
    if not exists (
        select 1
        from pg_trigger
        where tgname = 'trg_telegram_subscribers_updated_at'
    ) then
        create trigger trg_telegram_subscribers_updated_at
        before update on public.telegram_subscribers
        for each row
        execute function public.set_updated_at();
    end if;
end$$;

alter table public.telegram_subscribers enable row level security;
alter table public.notification_deliveries enable row level security;

-- Intentionally no anon/auth policies here.
-- Access should happen through trusted backend channels (Edge Functions with secret key).
